
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq-resolver
  labels:
    app: dnsmasq-resolver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnsmasq-resolver
  template:
    metadata:
      labels:
        app: dnsmasq-resolver
    spec:
      containers:
      - name: dnsmasq
        image: rogersbernat/dnsmasq:latest
        ports:
        - containerPort: 53
        resources:
          requests:
            memory: 20Mi
            cpu: 5m
          limits:
            memory: 25Mi
            cpu: 50m
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 8.8.4.4
        searches:
          - ns1.svc.cluster-domain.example
          - my.dns.search.suffix
---
apiVersion: v1
kind: Service
metadata:
  name: dns-service
spec:
  selector:
    app: dnsmasq-resolver
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53