
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
  labels:
    app: debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugger
  template:
    metadata:
      labels:
        app: debugger
    spec:
      containers:
      - name: debugger
        image: rogersbernat/debug-tools:latest
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - ip-dnsmasq-service
        searches:
          - ns1.svc.cluster-domain.example
          - my.dns.search.suffix
          